rm(list=ls())

#package check & install & load
install.packages("readr")
library(readr)

# 형태소분석 완료된 문서 가져오기
parsedData =read.csv("D:/Users/KEI/Desktop/total_0620/out_total.csv")
View(parsedData)

# Emojis Pre-processing
# 1. Smileys Emojis
for (j in seq(parsedData)) {
  parsedData[[j]] <- gsub("😀","이를 드러내고 활짝 웃는 얼굴", parsedData[[j]])
  parsedData[[j]] <- gsub("😬", "찡그린 얼굴", parsedData[[j]])
  parsedData[[j]] <- gsub("😁", "미소 짓는 눈으로 웃는 얼굴", parsedData[[j]])
  parsedData[[j]] <- gsub("😂", "기쁨의 눈물을 흘리는 얼굴", parsedData[[j]])
  parsedData[[j]] <- gsub("😃", "입을 벌리고 웃는 얼굴", parsedData[[j]])
  parsedData[[j]] <- gsub("😄", "입을 벌리고 미소 짓는 눈으로 웃는 얼굴", parsedData[[j]])
  parsedData[[j]] <- gsub("🤣", "데굴데굴 구르며 웃는 얼굴", parsedData[[j]])
  parsedData[[j]] <- gsub("😅", "입을 벌리고 식은땀을 흘리며 웃는 얼굴", parsedData[[j]])
  parsedData[[j]] <- gsub("😆", "입을 벌리고 눈을 꼭 감은 채로 웃는 얼굴", parsedData[[j]])
  parsedData[[j]] <- gsub("😇", "후광이 있는 웃는 얼굴", parsedData[[j]])
  parsedData[[j]] <- gsub("😉", "윙크하는 얼굴", parsedData[[j]])
  parsedData[[j]] <- gsub("😊", "미소 짓는 눈으로 웃는 얼굴", parsedData[[j]])
  parsedData[[j]] <- gsub("🙂", "살짝 웃는 얼굴", parsedData[[j]])
  parsedData[[j]] <- gsub("🙃", "뒤집어진 얼굴", parsedData[[j]])
  parsedData[[j]] <- gsub("☺", "웃는 흰색 얼굴", parsedData[[j]])
  parsedData[[j]] <- gsub("😋", "맛있는 음식을 음미하는 얼굴", parsedData[[j]])
  parsedData[[j]] <- gsub("😌", "안심하는 얼굴", parsedData[[j]])
  parsedData[[j]] <- gsub("😍", "하트 눈으로 웃는 얼굴", parsedData[[j]])
  parsedData[[j]] <- gsub("😘", "키스를 날리는 얼굴", parsedData[[j]])
  parsedData[[j]] <- gsub("😗", "키스하는 얼굴", parsedData[[j]])
  parsedData[[j]] <- gsub("😙", "미소 짓는 눈으로 키스하는 얼굴", parsedData[[j]])
  parsedData[[j]] <- gsub("😚", "눈을 감은 채 키스하는 얼굴", parsedData[[j]])
  parsedData[[j]] <- gsub("😜", "윙크하며 메롱 하는 얼굴", parsedData[[j]])
  parsedData[[j]] <- gsub("😝", "눈을 꼭 감은 채 메롱 하는 얼굴", parsedData[[j]])
  parsedData[[j]] <- gsub("😛", "메롱 하는 얼굴", parsedData[[j]])
  parsedData[[j]] <- gsub("🤑", "입이 돈으로 된 얼굴", parsedData[[j]])
  parsedData[[j]] <- gsub("😎", "선글라스를 쓰고 웃는 얼굴", parsedData[[j]])
  parsedData[[j]] <- gsub("😎", "선글라스를 쓰고 웃는 얼굴", parsedData[[j]])
  parsedData[[j]] <- gsub("🤓", "괴짜 얼굴", parsedData[[j]])
  parsedData[[j]] <- gsub("🤠", "카우보이 모자를 쓴 얼굴", parsedData[[j]])
  parsedData[[j]] <- gsub("🤗", "포옹하는 얼굴", parsedData[[j]])
  parsedData[[j]] <- gsub("🤡", "삐에로 얼굴", parsedData[[j]])
  parsedData[[j]] <- gsub("😏", "능글맞게 웃는 얼굴", parsedData[[j]])
  parsedData[[j]] <- gsub("😶", "입이 없는 얼굴", parsedData[[j]])
  parsedData[[j]] <- gsub("😐", "감정을 드러내지 않은 얼굴", parsedData[[j]])
  parsedData[[j]] <- gsub("😑", "무표정한 얼굴", parsedData[[j]])
  parsedData[[j]] <- gsub("😒", "지루해하는 얼굴", parsedData[[j]])
  parsedData[[j]] <- gsub("🙄", "눈을 굴리는 얼굴", parsedData[[j]])
  parsedData[[j]] <- gsub("🤔", "생각하는 얼굴", parsedData[[j]])
  parsedData[[j]] <- gsub("🤥", "거짓말하는 얼굴", parsedData[[j]])
  parsedData[[j]] <- gsub("😳", "빨개진 얼굴", parsedData[[j]])
  parsedData[[j]] <- gsub("😞", "실망한 얼굴", parsedData[[j]])
  parsedData[[j]] <- gsub("😟", "걱정하는 얼굴", parsedData[[j]])
  parsedData[[j]] <- gsub("😠", "화난 얼굴", parsedData[[j]])
  parsedData[[j]] <- gsub("😡", "입을 삐죽 내민 얼굴", parsedData[[j]])
  parsedData[[j]] <- gsub("😔", "사색에 잠긴 얼굴", parsedData[[j]])
  parsedData[[j]] <- gsub("😕", "혼란에 빠진 얼굴", parsedData[[j]])
  parsedData[[j]] <- gsub("🙁", "약간 찌푸린 얼굴", parsedData[[j]])
  parsedData[[j]] <- gsub("☹", "찌푸린 얼굴", parsedData[[j]])
  parsedData[[j]] <- gsub("😣", "인내하는 얼굴", parsedData[[j]])
  parsedData[[j]] <- gsub("😖", "당혹해하는 얼굴", parsedData[[j]])
  parsedData[[j]] <- gsub("😫", "피곤해하는 얼굴", parsedData[[j]])
  parsedData[[j]] <- gsub("😩", "지친 얼굴", parsedData[[j]])
  parsedData[[j]] <- gsub("😤", "의기양양한 얼굴", parsedData[[j]])
  parsedData[[j]] <- gsub("😮", "입을 벌린 얼굴", parsedData[[j]])
  parsedData[[j]] <- gsub("😱", "공포의 비명을 지르는 얼굴", parsedData[[j]])
  parsedData[[j]] <- gsub("😨", "두려워하는 얼굴", parsedData[[j]])
  parsedData[[j]] <- gsub("😰", "입을 벌리고 식은땀 흘리는 얼굴", parsedData[[j]])
  parsedData[[j]] <- gsub("😯", "숨죽인 얼굴", parsedData[[j]])
  parsedData[[j]] <- gsub("😦", "입을 벌리고 찡그리는 얼굴", parsedData[[j]])
  parsedData[[j]] <- gsub("😧", "고뇌에 찬 얼굴", parsedData[[j]])
  parsedData[[j]] <- gsub("😢", "우는 얼굴", parsedData[[j]])
  parsedData[[j]] <- gsub("😥", "실망하지만 안심하는 얼굴", parsedData[[j]])
  parsedData[[j]] <- gsub("😪", "졸린 얼굴", parsedData[[j]])
  parsedData[[j]] <- gsub("🤤", "침 흘리는 얼굴", parsedData[[j]])
  parsedData[[j]] <- gsub("😓", "식은땀 나는 얼굴", parsedData[[j]])
  parsedData[[j]] <- gsub("😭", "엉엉 우는 얼굴", parsedData[[j]])
  parsedData[[j]] <- gsub("😵", "어지러워하는 얼굴", parsedData[[j]])
  parsedData[[j]] <- gsub("😲", "놀라는 얼굴", parsedData[[j]])
  parsedData[[j]] <- gsub("🤐", "입이 지퍼로 된 얼굴", parsedData[[j]])
  parsedData[[j]] <- gsub("😷", "마스크를 한 얼굴", parsedData[[j]])
  parsedData[[j]] <- gsub("🤕", "머리에 붕대를 감은 얼굴", parsedData[[j]])
  parsedData[[j]] <- gsub("🤒", "온도계를 문 얼굴", parsedData[[j]])
  parsedData[[j]] <- gsub("🤢", "메스꺼워하는 얼굴", parsedData[[j]])
  parsedData[[j]] <- gsub("🤧", "재채기하는 얼굴", parsedData[[j]])
  parsedData[[j]] <- gsub("😴", "잠자는 얼굴", parsedData[[j]])
  parsedData[[j]] <- gsub("💤", "수면 기호", parsedData[[j]])
  parsedData[[j]] <- gsub("😈", "뿔 달린 웃는 얼굴", parsedData[[j]])
  parsedData[[j]] <- gsub("👿", "꼬마 도깨비", parsedData[[j]])
  parsedData[[j]] <- gsub("💩", "똥 더미", parsedData[[j]])
  parsedData[[j]] <- gsub("👻", "유령", parsedData[[j]])
  parsedData[[j]] <- gsub("💀", "해골", parsedData[[j]])
  parsedData[[j]] <- gsub("☠", "해골 및 교차된 뼈", parsedData[[j]])
  parsedData[[j]] <- gsub("👽", "외계인", parsedData[[j]])
  parsedData[[j]] <- gsub("🤖", "로봇 얼굴", parsedData[[j]])
  parsedData[[j]] <- gsub("🎃", "호박 초롱", parsedData[[j]])
  parsedData[[j]] <- gsub("😺", "입을 벌리고 웃는 고양이 얼굴", parsedData[[j]])
  parsedData[[j]] <- gsub("😸", "미소 짓는 눈으로 웃는 고양이 얼굴", parsedData[[j]])
  parsedData[[j]] <- gsub("😹", "기쁨의 눈물을 흘리는 고양이 얼굴", parsedData[[j]])
  parsedData[[j]] <- gsub("😻", "하트 눈으로 웃는 고양이 얼굴", parsedData[[j]])
  parsedData[[j]] <- gsub("😼", "쓴웃음을 짓는 고양이 얼굴", parsedData[[j]])
  parsedData[[j]] <- gsub("😽", "눈을 감은 채 키스하는 고양이 얼굴", parsedData[[j]])
  parsedData[[j]] <- gsub("🙀", "똥 더미", parsedData[[j]])
  parsedData[[j]] <- gsub("😿", "유령", parsedData[[j]])
  parsedData[[j]] <- gsub("😾", "입을 삐죽 내민 고양이 얼굴", parsedData[[j]])
}
# 2. People and Fantasy Emojis
for (j in seq(parsedData)) {
  parsedData[[j]] <- gsub("👐", "양손을 벌린 기호", parsedData[[j]])
  parsedData[[j]] <- gsub("🙌", "두 손을 들고 축하하는 사람", parsedData[[j]])
  parsedData[[j]] <- gsub("👏", "손뼉 치는 손 기호", parsedData[[j]])
  parsedData[[j]] <- gsub("🙏", "두 손을 모은 사람", parsedData[[j]])
  parsedData[[j]] <- gsub("🤝", "악수", parsedData[[j]])
  parsedData[[j]] <- gsub("👍", "엄지를 올린 손 기호", parsedData[[j]])
  parsedData[[j]] <- gsub("👎", "엄지를 내린 손 기호", parsedData[[j]])
  parsedData[[j]] <- gsub("👊", "주먹 기호", parsedData[[j]])
  parsedData[[j]] <- gsub("✊", "위를 향한 주먹", parsedData[[j]])
  parsedData[[j]] <- gsub("🤛", "왼쪽을 향한 주먹", parsedData[[j]])
  parsedData[[j]] <- gsub("🤜", "오른쪽을 향한 주먹", parsedData[[j]])
  parsedData[[j]] <- gsub("🤞", "행운을 비는 손가락 제스쳐", parsedData[[j]])
  parsedData[[j]] <- gsub("✌", "승리의 V를 한 손", parsedData[[j]])
  parsedData[[j]] <- gsub("🤘", "사인 오브 더 혼스", parsedData[[j]])
  parsedData[[j]] <- gsub("👌", "OK 하는 손 기호", parsedData[[j]])
  parsedData[[j]] <- gsub("👈", "검지가 왼쪽을 가리키는 흰색 손등", parsedData[[j]])
  parsedData[[j]] <- gsub("👉", "검지가 오른쪽을 가리키는 흰색 손등", parsedData[[j]])
  parsedData[[j]] <- gsub("👆", "검지가 위를 가리키는 흰색 손등", parsedData[[j]])
  parsedData[[j]] <- gsub("👇", "검지가 아래를 가리키는 흰색 손등", parsedData[[j]])
  parsedData[[j]] <- gsub("☝", "위를 가리키는 흰색 검지", parsedData[[j]])
  parsedData[[j]] <- gsub("✋", "위를 향한 손", parsedData[[j]])
  parsedData[[j]] <- gsub("🤚", "펼친 손등", parsedData[[j]])
  parsedData[[j]] <- gsub("🖐", "손가락을 펼치고 들어올린 손", parsedData[[j]])
  parsedData[[j]] <- gsub("🖖", "중지와 약지 사이를 벌리고 들어올린 손", parsedData[[j]])
  parsedData[[j]] <- gsub("👋", "손을 흔드는 기호", parsedData[[j]])
  parsedData[[j]] <- gsub("🤙", "전화해 손", parsedData[[j]])
  parsedData[[j]] <- gsub("💪", "울퉁불퉁한 이두박근", parsedData[[j]])
  parsedData[[j]] <- gsub("🖕", "세 번째 손가락을 펼친 뒤집은 손", parsedData[[j]])
  parsedData[[j]] <- gsub("✍", "글씨 쓰는 손", parsedData[[j]])
  parsedData[[j]] <- gsub("🏼", "살색", parsedData[[j]])
  parsedData[[j]] <- gsub("🏻", "밝은 살색", parsedData[[j]])
  parsedData[[j]] <- gsub("🤳", "셀카", parsedData[[j]])
  parsedData[[j]] <- gsub("💅", "매니큐어", parsedData[[j]])
  parsedData[[j]] <- gsub("👄", "입", parsedData[[j]])
  parsedData[[j]] <- gsub("👅", "혀", parsedData[[j]])
  parsedData[[j]] <- gsub("👂", "귀", parsedData[[j]])
  parsedData[[j]] <- gsub("👃", "코", parsedData[[j]])
  parsedData[[j]] <- gsub("👁", "눈", parsedData[[j]])
  parsedData[[j]] <- gsub("👀", "눈", parsedData[[j]])
  parsedData[[j]] <- gsub("💦", "땀", parsedData[[j]])
  parsedData[[j]] <- gsub("👤", "상반신 실루엣", parsedData[[j]])
  parsedData[[j]] <- gsub("👥", "여러 명의 상반신 실루엣", parsedData[[j]])
  parsedData[[j]] <- gsub("🗣", "말하는 사람의 머리 실루엣", parsedData[[j]])
  parsedData[[j]] <- gsub("👶", "아기", parsedData[[j]])
  parsedData[[j]] <- gsub("👦", "소년", parsedData[[j]])
  parsedData[[j]] <- gsub("👧", "소녀", parsedData[[j]])
  parsedData[[j]] <- gsub("👨", "남자", parsedData[[j]])
  parsedData[[j]] <- gsub("👩", "여자", parsedData[[j]])
  parsedData[[j]] <- gsub("👴", "할아버지", parsedData[[j]])
  parsedData[[j]] <- gsub("👵", "할머니", parsedData[[j]])
  parsedData[[j]] <- gsub("👲", "중국 전통 모자를 쓴 남자", parsedData[[j]])
  parsedData[[j]] <- gsub("🤶", "산타 할머니", parsedData[[j]])
  parsedData[[j]] <- gsub("🎅", "산타클로스", parsedData[[j]])
  parsedData[[j]] <- gsub("👼", "아기 천사", parsedData[[j]])
  parsedData[[j]] <- gsub("👸", "공주", parsedData[[j]])
  parsedData[[j]] <- gsub("🤴", "왕자", parsedData[[j]])
  parsedData[[j]] <- gsub("👰", "면사포를 쓴 신부", parsedData[[j]])
  parsedData[[j]] <- gsub("🙋", "손을 들고 있는 여자", parsedData[[j]])
  parsedData[[j]] <- gsub("🙆", "좋다는 제스처의 여자", parsedData[[j]])
  parsedData[[j]] <- gsub("🙅", "안 좋다는 제스처의 여자", parsedData[[j]]) 
  parsedData[[j]] <- gsub("🤰", "임산부", parsedData[[j]])
  parsedData[[j]] <- gsub("👫", "손을 잡고 있는 남자와 여자", parsedData[[j]])
  parsedData[[j]] <- gsub("👬", "손을 잡고 있는 두 남자", parsedData[[j]])
  parsedData[[j]] <- gsub("👭", "손을 잡고 있는 두 여자", parsedData[[j]])
  parsedData[[j]] <- gsub("💑", "연인과 하트", parsedData[[j]])
  parsedData[[j]] <- gsub("💏", "키스", parsedData[[j]])
  parsedData[[j]] <- gsub("👪", "가족", parsedData[[j]])
}
# 3. Clothing and Accessories Emojis
for (j in seq(parsedData)) {
  parsedData[[j]] <- gsub("👚", "블라우스", parsedData[[j]])
  parsedData[[j]] <- gsub("👕", "티셔츠", parsedData[[j]])
  parsedData[[j]] <- gsub("👖", "청바지", parsedData[[j]])
  parsedData[[j]] <- gsub("👔", "넥타이", parsedData[[j]])
  parsedData[[j]] <- gsub("👗", "원피스", parsedData[[j]])
  parsedData[[j]] <- gsub("👙", "비키니", parsedData[[j]])
  parsedData[[j]] <- gsub("👘", "기모노", parsedData[[j]])
  parsedData[[j]] <- gsub("💄", "립스틱", parsedData[[j]])
  parsedData[[j]] <- gsub("💋", "키스 자국", parsedData[[j]])
  parsedData[[j]] <- gsub("👣", "발자국", parsedData[[j]])
  parsedData[[j]] <- gsub("👠", "하이힐", parsedData[[j]])
  parsedData[[j]] <- gsub("👡", "여성 샌들", parsedData[[j]])
  parsedData[[j]] <- gsub("👢", "여성 부츠", parsedData[[j]])
  parsedData[[j]] <- gsub("👞", "남성 구두", parsedData[[j]])
  parsedData[[j]] <- gsub("👟", "운동화", parsedData[[j]])
  parsedData[[j]] <- gsub("👒", "여성용 모자", parsedData[[j]])
  parsedData[[j]] <- gsub("🎩", "중산모", parsedData[[j]])
  parsedData[[j]] <- gsub("🎓", "학사모", parsedData[[j]])
  parsedData[[j]] <- gsub("👑", "왕관", parsedData[[j]])
  parsedData[[j]] <- gsub("⛑", "하얀 십자가가 그려진 헬멧", parsedData[[j]])
  parsedData[[j]] <- gsub("🎒", "책가방", parsedData[[j]])
  parsedData[[j]] <- gsub("👝", "파우치", parsedData[[j]])
  parsedData[[j]] <- gsub("👛", "지갑", parsedData[[j]])
  parsedData[[j]] <- gsub("👜", "핸드백", parsedData[[j]])
  parsedData[[j]] <- gsub("💼", "서류 가방", parsedData[[j]])
  parsedData[[j]] <- gsub("👓", "안경", parsedData[[j]])
  parsedData[[j]] <- gsub("🕶", "짙은 선글라스", parsedData[[j]])
  parsedData[[j]] <- gsub("💍", "반지", parsedData[[j]])
  parsedData[[j]] <- gsub("🌂", "접은 우산", parsedData[[j]])
  parsedData[[j]] <- gsub("☂", "우산", parsedData[[j]])
}
# 4. Animals and Nature Emojis
for (j in seq(parsedData)) {
  parsedData[[j]] <- gsub("🐶", "개 얼굴", parsedData[[j]])
  parsedData[[j]] <- gsub("🐱", "고양이 얼굴", parsedData[[j]])
  parsedData[[j]] <- gsub("🐭", "생쥐 얼굴", parsedData[[j]])
  parsedData[[j]] <- gsub("🐹", "햄스터 얼굴", parsedData[[j]])
  parsedData[[j]] <- gsub("🐰", "토끼 얼굴", parsedData[[j]])
  parsedData[[j]] <- gsub("🐻", "곰 얼굴", parsedData[[j]])
  parsedData[[j]] <- gsub("🐼", "판다 얼굴", parsedData[[j]])
  parsedData[[j]] <- gsub("🐨", "코알라", parsedData[[j]])
  parsedData[[j]] <- gsub("🐯", "호랑이 얼굴", parsedData[[j]])
  parsedData[[j]] <- gsub("🦁", "사자 얼굴", parsedData[[j]])
  parsedData[[j]] <- gsub("🐮", "소 얼굴", parsedData[[j]])
  parsedData[[j]] <- gsub("🐷", "돼지 얼굴", parsedData[[j]])
  parsedData[[j]] <- gsub("🐽", "돼지 코", parsedData[[j]])
  parsedData[[j]] <- gsub("🐸", "개구리 얼굴", parsedData[[j]])
  parsedData[[j]] <- gsub("🐵", "원숭이 얼굴", parsedData[[j]])
  parsedData[[j]] <- gsub("🙈", "눈을 가린 원숭이", parsedData[[j]])
  parsedData[[j]] <- gsub("🙉", "귀를 막은 원숭이", parsedData[[j]])
  parsedData[[j]] <- gsub("🙊", "입을 막은 원숭이", parsedData[[j]])
  parsedData[[j]] <- gsub("🐒", "원숭이", parsedData[[j]])
  parsedData[[j]] <- gsub("🦍", "고릴라", parsedData[[j]])
  parsedData[[j]] <- gsub("🐔", "닭", parsedData[[j]])
  parsedData[[j]] <- gsub("🐧", "펭귄", parsedData[[j]])
  parsedData[[j]] <- gsub("🐦", "새", parsedData[[j]])
  parsedData[[j]] <- gsub("🐤", "병아리 옆모습", parsedData[[j]])
  parsedData[[j]] <- gsub("🐣", "알 까는 병아리", parsedData[[j]])
  parsedData[[j]] <- gsub("🐥", "병아리 앞모습", parsedData[[j]])
  parsedData[[j]] <- gsub("🐺", "늑대 얼굴", parsedData[[j]])
  parsedData[[j]] <- gsub("🦊", "여우 얼굴", parsedData[[j]])
  parsedData[[j]] <- gsub("🐗", "수퇘지", parsedData[[j]])
  parsedData[[j]] <- gsub("🐴", "말 얼굴", parsedData[[j]])
  parsedData[[j]] <- gsub("🦌", "사슴", parsedData[[j]])
  parsedData[[j]] <- gsub("🦄", "유니콘 얼굴", parsedData[[j]])
  parsedData[[j]] <- gsub("🐝", "꿀벌", parsedData[[j]])
  parsedData[[j]] <- gsub("🐛", "벌레", parsedData[[j]])
  parsedData[[j]] <- gsub("🦋", "나비", parsedData[[j]])
  parsedData[[j]] <- gsub("🐌", "달팽이", parsedData[[j]])
  parsedData[[j]] <- gsub("🐞", "무당벌레", parsedData[[j]])
  parsedData[[j]] <- gsub("🐜", "개미", parsedData[[j]])
  parsedData[[j]] <- gsub("🕷", "거미", parsedData[[j]])
  parsedData[[j]] <- gsub("🕸", "거미줄", parsedData[[j]])
  parsedData[[j]] <- gsub("🦂", "전갈", parsedData[[j]])
  parsedData[[j]] <- gsub("🐢", "거북이", parsedData[[j]])
  parsedData[[j]] <- gsub("🐍", "뱀", parsedData[[j]])
  parsedData[[j]] <- gsub("🦎", "도마뱀", parsedData[[j]])
  parsedData[[j]] <- gsub("🦀", "게", parsedData[[j]])
  parsedData[[j]] <- gsub("🦑", "오징어", parsedData[[j]])
  parsedData[[j]] <- gsub("🐙", "문어", parsedData[[j]])
  parsedData[[j]] <- gsub("🦐", "새우", parsedData[[j]])
  parsedData[[j]] <- gsub("🐠", "열대어", parsedData[[j]])
  parsedData[[j]] <- gsub("🐟", "물고기", parsedData[[j]])
  parsedData[[j]] <- gsub("🐡", "복어", parsedData[[j]])
  parsedData[[j]] <- gsub("🐬", "돌고래", parsedData[[j]])
  parsedData[[j]] <- gsub("🦈", "상어", parsedData[[j]])
  parsedData[[j]] <- gsub("🐳", "물 뿜는 고래", parsedData[[j]])
  parsedData[[j]] <- gsub("🐋", "고래", parsedData[[j]])
  parsedData[[j]] <- gsub("🐊", "악어", parsedData[[j]])
  parsedData[[j]] <- gsub("🐆", "표범", parsedData[[j]])
  parsedData[[j]] <- gsub("🐅", "호랑이", parsedData[[j]])
  parsedData[[j]] <- gsub("🐃", "물소", parsedData[[j]])
  parsedData[[j]] <- gsub("🐂", "소", parsedData[[j]])
  parsedData[[j]] <- gsub("🐄", "소", parsedData[[j]])
  parsedData[[j]] <- gsub("🐪", "단봉낙타", parsedData[[j]])
  parsedData[[j]] <- gsub("🐫", "쌍봉낙타", parsedData[[j]])
  parsedData[[j]] <- gsub("🐘", "코끼리", parsedData[[j]])
  parsedData[[j]] <- gsub("🦏", "코뿔소", parsedData[[j]])
  parsedData[[j]] <- gsub("🐐", "염소", parsedData[[j]])
  parsedData[[j]] <- gsub("🐏", "숫양", parsedData[[j]])
  parsedData[[j]] <- gsub("🐑", "양", parsedData[[j]])
  parsedData[[j]] <- gsub("🐎", "말", parsedData[[j]])
  parsedData[[j]] <- gsub("🐖", "돼지", parsedData[[j]])
  parsedData[[j]] <- gsub("🦇", "박쥐", parsedData[[j]])
  parsedData[[j]] <- gsub("🐓", "수탉", parsedData[[j]])
  parsedData[[j]] <- gsub("🦃", "터키", parsedData[[j]])
  parsedData[[j]] <- gsub("🕊", "평화의 비둘기", parsedData[[j]])
  parsedData[[j]] <- gsub("🦅", "독수리", parsedData[[j]])
  parsedData[[j]] <- gsub("🦆", "오리", parsedData[[j]])
  parsedData[[j]] <- gsub("🦉", "부엉이", parsedData[[j]])
  parsedData[[j]] <- gsub("🐕", "개", parsedData[[j]])
  parsedData[[j]] <- gsub("🐩", "푸들", parsedData[[j]])
  parsedData[[j]] <- gsub("🐈", "고양이", parsedData[[j]])
  parsedData[[j]] <- gsub("🐇", "토끼", parsedData[[j]])
  parsedData[[j]] <- gsub("🐀", "쥐", parsedData[[j]])
  parsedData[[j]] <- gsub("🐁", "생쥐", parsedData[[j]])
  parsedData[[j]] <- gsub("🐿", "다람쥐", parsedData[[j]])
  parsedData[[j]] <- gsub("🐾", "고슴도치", parsedData[[j]])
  parsedData[[j]] <- gsub("🐉", "동물 발자국", parsedData[[j]])
  parsedData[[j]] <- gsub("🐲", "용", parsedData[[j]])
  parsedData[[j]] <- gsub("🌵", "용 얼굴", parsedData[[j]])
  parsedData[[j]] <- gsub("🎄", "선인장", parsedData[[j]])
  parsedData[[j]] <- gsub("🌲", "크리스마스 트리", parsedData[[j]])
  parsedData[[j]] <- gsub("🌳", "상록수", parsedData[[j]])
  parsedData[[j]] <- gsub("🌴", "낙엽수", parsedData[[j]])
  parsedData[[j]] <- gsub("🌱", "야자나무", parsedData[[j]])
  parsedData[[j]] <- gsub("🌿", "묘목", parsedData[[j]])
  parsedData[[j]] <- gsub("☘", "허브", parsedData[[j]])
  parsedData[[j]] <- gsub("🍀", "토끼풀", parsedData[[j]])
  parsedData[[j]] <- gsub("🎍", "네 잎 클로버", parsedData[[j]])
  parsedData[[j]] <- gsub("🎋", "소나무 장식", parsedData[[j]])
  parsedData[[j]] <- gsub("🍃", "일본 칠석제 나무", parsedData[[j]])
  parsedData[[j]] <- gsub("🍂", "바람에 흩날리는 잎", parsedData[[j]])
  parsedData[[j]] <- gsub("🍁", "낙엽", parsedData[[j]])
  parsedData[[j]] <- gsub("🌾", "단풍잎", parsedData[[j]])
  parsedData[[j]] <- gsub("🌺", "벼 이삭", parsedData[[j]])
  parsedData[[j]] <- gsub("🌻", "무궁화", parsedData[[j]])
  parsedData[[j]] <- gsub("🌹", "해바라기", parsedData[[j]])
  parsedData[[j]] <- gsub("🥀", "장미", parsedData[[j]])
  parsedData[[j]] <- gsub("🌷", "시든 꽃", parsedData[[j]])
  parsedData[[j]] <- gsub("🌼", "튤립", parsedData[[j]])
  parsedData[[j]] <- gsub("🌸", "꽃", parsedData[[j]])
  parsedData[[j]] <- gsub("💐", "벚꽃", parsedData[[j]])
  parsedData[[j]] <- gsub("🍄", "부케", parsedData[[j]])
  parsedData[[j]] <- gsub("🌰", "버섯", parsedData[[j]])
  parsedData[[j]] <- gsub("🐚", "밤", parsedData[[j]])
  parsedData[[j]] <- gsub("🌎", "소라껍데기", parsedData[[j]])
  parsedData[[j]] <- gsub("🌍", "지구본 미주", parsedData[[j]])
  parsedData[[j]] <- gsub("🌏", "지구본 유럽-아프리카", parsedData[[j]])
  parsedData[[j]] <- gsub("🌕", "지구본 아시아-오세아니아", parsedData[[j]])
  parsedData[[j]] <- gsub("🌖", "보름달 기호", parsedData[[j]])
  parsedData[[j]] <- gsub("🌗", "망현간 철월 기호", parsedData[[j]])
  parsedData[[j]] <- gsub("🌘", "하현달 기호", parsedData[[j]])
  parsedData[[j]] <- gsub("🌑", "현삭간 요월 기호", parsedData[[j]])
  parsedData[[j]] <- gsub("🌒", "삭 기호", parsedData[[j]])
  parsedData[[j]] <- gsub("🌓", "삭현간 요월 기호", parsedData[[j]])
  parsedData[[j]] <- gsub("🌔", "상현달 기호", parsedData[[j]])
  parsedData[[j]] <- gsub("🌚", "현망간 철월 기호", parsedData[[j]])
  parsedData[[j]] <- gsub("🌝", "얼굴이 있는 삭", parsedData[[j]])
  parsedData[[j]] <- gsub("🌛", "얼굴이 있는 보름달", parsedData[[j]])
  parsedData[[j]] <- gsub("🌜", "얼굴이 있는 상현달", parsedData[[j]])
  parsedData[[j]] <- gsub("🌞", "얼굴이 있는 하현달", parsedData[[j]])
  parsedData[[j]] <- gsub("🌙", "얼굴이 있는 태양", parsedData[[j]])
  parsedData[[j]] <- gsub("⭐", "초승달", parsedData[[j]])
  parsedData[[j]] <- gsub("🌟", "중간 크기의 흰색 화살표", parsedData[[j]])
  parsedData[[j]] <- gsub("💫", "반짝이는 별", parsedData[[j]])
  parsedData[[j]] <- gsub("✨", "어지러움 기호", parsedData[[j]])
  parsedData[[j]] <- gsub("☄", "반짝임", parsedData[[j]])
  parsedData[[j]] <- gsub("☀", "혜성", parsedData[[j]])
  parsedData[[j]] <- gsub("🌤", "햇살이 있는 검은색 태양", parsedData[[j]])
  parsedData[[j]] <- gsub("⛅", "작은 구름과 태양", parsedData[[j]])
  parsedData[[j]] <- gsub("🌥", "구름에 가려진 태양", parsedData[[j]])
  parsedData[[j]] <- gsub("🌦", "구름 뒤의 태양", parsedData[[j]])
  parsedData[[j]] <- gsub("☁", "비가 내리는 구름에 가려진 태양", parsedData[[j]])
  parsedData[[j]] <- gsub("🌧", "구름", parsedData[[j]])
  parsedData[[j]] <- gsub("⛈", "비가 내리는 구름", parsedData[[j]])
  parsedData[[j]] <- gsub("🌩", "비가 내리는 뇌운", parsedData[[j]])
  parsedData[[j]] <- gsub("⚡", "번개가 치는 구름", parsedData[[j]])
  parsedData[[j]] <- gsub("🔥", "고압 전류 기호", parsedData[[j]])
  parsedData[[j]] <- gsub("💥", "불", parsedData[[j]])
  parsedData[[j]] <- gsub("❄", "충돌 기호", parsedData[[j]])
  parsedData[[j]] <- gsub("🌨", "눈송이", parsedData[[j]])
  parsedData[[j]] <- gsub("☃", "눈이 내리는 구름", parsedData[[j]])
  parsedData[[j]] <- gsub("⛄", "눈사람", parsedData[[j]])
  parsedData[[j]] <- gsub("🌬", "눈송이 없는 눈사람", parsedData[[j]])
  parsedData[[j]] <- gsub("💨", "바람을 내뿜는 얼굴", parsedData[[j]])
  parsedData[[j]] <- gsub("🌪", "대시 기호", parsedData[[j]])
  parsedData[[j]] <- gsub("🌫", "토네이도와 구름", parsedData[[j]])
  parsedData[[j]] <- gsub("☔", "안개", parsedData[[j]])
}
# 5. Food & Drink Emojis
for (j in seq(parsedData)) {
  parsedData[[j]] <- gsub("🍎", "빨간 사과", parsedData[[j]])
  parsedData[[j]] <- gsub("🍐", "배", parsedData[[j]])
  parsedData[[j]] <- gsub("🍊", "귤", parsedData[[j]])
  parsedData[[j]] <- gsub("🍋", "레몬", parsedData[[j]])
  parsedData[[j]] <- gsub("🍌", "바나나", parsedData[[j]])
  parsedData[[j]] <- gsub("🍉", "수박", parsedData[[j]])
  parsedData[[j]] <- gsub("🍇", "포도", parsedData[[j]])
  parsedData[[j]] <- gsub("🍓", "딸기", parsedData[[j]])
  parsedData[[j]] <- gsub("🍈", "멜론", parsedData[[j]])
  parsedData[[j]] <- gsub("🍒", "체리", parsedData[[j]])
  parsedData[[j]] <- gsub("🍑", "복숭아", parsedData[[j]])
  parsedData[[j]] <- gsub("🍍", "파인애플", parsedData[[j]])
  parsedData[[j]] <- gsub("🥝", "키위", parsedData[[j]])
  parsedData[[j]] <- gsub("🍅", "토마토", parsedData[[j]])
  parsedData[[j]] <- gsub("🥑", "아보카도", parsedData[[j]])
  parsedData[[j]] <- gsub("🍆", "가지", parsedData[[j]])
  parsedData[[j]] <- gsub("🌶", "고추", parsedData[[j]])
  parsedData[[j]] <- gsub("🥒", "오이", parsedData[[j]])
  parsedData[[j]] <- gsub("🌽", "옥수수", parsedData[[j]])
  parsedData[[j]] <- gsub("🥕", "당근", parsedData[[j]])
  parsedData[[j]] <- gsub("🥗", "야채 샐러드", parsedData[[j]])
  parsedData[[j]] <- gsub("🥔", "감자", parsedData[[j]])
  parsedData[[j]] <- gsub("🍠", "군고구마", parsedData[[j]])
  parsedData[[j]] <- gsub("🥜", "땅콩", parsedData[[j]])
  parsedData[[j]] <- gsub("🍯", "꿀단지", parsedData[[j]])
  parsedData[[j]] <- gsub("🍞", "빵", parsedData[[j]])
  parsedData[[j]] <- gsub("🥐", "크루아상", parsedData[[j]])
  parsedData[[j]] <- gsub("🥖", "바게트 빵", parsedData[[j]])
  parsedData[[j]] <- gsub("🥞", "팬케이크", parsedData[[j]])
  parsedData[[j]] <- gsub("🧀", "치즈 조각", parsedData[[j]])
  parsedData[[j]] <- gsub("🍗", "닭다리", parsedData[[j]])
  parsedData[[j]] <- gsub("🍖", "뼈에 붙은 고기", parsedData[[j]])
  parsedData[[j]] <- gsub("🍤", "새우튀김", parsedData[[j]])
  parsedData[[j]] <- gsub("🥚", "계란", parsedData[[j]])
  parsedData[[j]] <- gsub("🍳", "프라이팬", parsedData[[j]])
  parsedData[[j]] <- gsub("🥓", "베이컨", parsedData[[j]])
  parsedData[[j]] <- gsub("🍔", "햄버거", parsedData[[j]])
  parsedData[[j]] <- gsub("🍟", "프렌치프라이", parsedData[[j]])
  parsedData[[j]] <- gsub("🌭", "핫도그", parsedData[[j]])
  parsedData[[j]] <- gsub("🍕", "피자 조각", parsedData[[j]])
  parsedData[[j]] <- gsub("🍝", "스파게티", parsedData[[j]])
  parsedData[[j]] <- gsub("🥙", "속을 채운 납작한 빵", parsedData[[j]])
  parsedData[[j]] <- gsub("🌮", "타코", parsedData[[j]])
  parsedData[[j]] <- gsub("🌯", "부리또", parsedData[[j]])
  parsedData[[j]] <- gsub("🍜", "라면", parsedData[[j]])
  parsedData[[j]] <- gsub("🥘", "빠에야", parsedData[[j]])
  parsedData[[j]] <- gsub("🍲", "전골냄비", parsedData[[j]])
  parsedData[[j]] <- gsub("🍥", "소용돌이무늬가 있는 어묵", parsedData[[j]])
  parsedData[[j]] <- gsub("🍣", "초밥", parsedData[[j]])
  parsedData[[j]] <- gsub("🍱", "도시락", parsedData[[j]])
  parsedData[[j]] <- gsub("🍛", "카레라이스", parsedData[[j]])
  parsedData[[j]] <- gsub("🍙", "주먹밥", parsedData[[j]])
  parsedData[[j]] <- gsub("🍚", "공기밥", parsedData[[j]])
  parsedData[[j]] <- gsub("🍘", "쌀 과자", parsedData[[j]])
  parsedData[[j]] <- gsub("🍢", "어묵 꼬지", parsedData[[j]])
  parsedData[[j]] <- gsub("🍡", "경단 꼬치", parsedData[[j]])
  parsedData[[j]] <- gsub("🍧", "빙수", parsedData[[j]])
  parsedData[[j]] <- gsub("🍨", "아이스크림", parsedData[[j]])
  parsedData[[j]] <- gsub("🍦", "소프트아이스크림", parsedData[[j]])
  parsedData[[j]] <- gsub("🍰", "조각 케이크", parsedData[[j]])
  parsedData[[j]] <- gsub("🎂", "생일 케이크", parsedData[[j]])
  parsedData[[j]] <- gsub("🍮", "푸딩", parsedData[[j]])
  parsedData[[j]] <- gsub("🍭", "막대 사탕", parsedData[[j]])
  parsedData[[j]] <- gsub("🍬", "사탕", parsedData[[j]])
  parsedData[[j]] <- gsub("🍫", "초콜릿 바", parsedData[[j]])
  parsedData[[j]] <- gsub("🍿", "팝콘", parsedData[[j]])
  parsedData[[j]] <- gsub("🍩", "도넛", parsedData[[j]])
  parsedData[[j]] <- gsub("🍪", "쿠키", parsedData[[j]])
  parsedData[[j]] <- gsub("☕", "뜨거운 음료", parsedData[[j]])
  parsedData[[j]] <- gsub("🍵", "손잡이 없는 찻잔", parsedData[[j]])
  parsedData[[j]] <- gsub("🍼", "젖병", parsedData[[j]])
  parsedData[[j]] <- gsub("🥛", "우유 한 잔", parsedData[[j]])
  parsedData[[j]] <- gsub("🍺", "맥주잔", parsedData[[j]])
  parsedData[[j]] <- gsub("🍻", "맥주잔 건배", parsedData[[j]])
  parsedData[[j]] <- gsub("🍷", "와인잔", parsedData[[j]])
  parsedData[[j]] <- gsub("🥂", "건배", parsedData[[j]])
  parsedData[[j]] <- gsub("🥃", "텀블러 잔", parsedData[[j]])
  parsedData[[j]] <- gsub("🍸", "칵테일잔", parsedData[[j]])
  parsedData[[j]] <- gsub("🍹", "열대음료", parsedData[[j]])
  parsedData[[j]] <- gsub("🍾", "코르크 마개가 있는 병", parsedData[[j]])
  parsedData[[j]] <- gsub("🍶", "술병과 잔", parsedData[[j]])
  parsedData[[j]] <- gsub("🥄", "숟가락", parsedData[[j]])
  parsedData[[j]] <- gsub("🍴", "포크와 나이프", parsedData[[j]])
  parsedData[[j]] <- gsub("🍽", "접시 및 포크와 나이프", parsedData[[j]])
}
# 6. Activity and Sports Emojis
for (j in seq(parsedData)) {
  parsedData[[j]] <- gsub("⚽", "축구공", parsedData[[j]])
  parsedData[[j]] <- gsub("🏀", "농구공과 농구 골대", parsedData[[j]])
  parsedData[[j]] <- gsub("🏈", "미식축구", parsedData[[j]])
  parsedData[[j]] <- gsub("🎾", "테니스 라켓과 공", parsedData[[j]])
  parsedData[[j]] <- gsub("🏐", "발리볼", parsedData[[j]])
  parsedData[[j]] <- gsub("🏉", "럭비", parsedData[[j]])
  parsedData[[j]] <- gsub("🎱", "당구", parsedData[[j]])
  parsedData[[j]] <- gsub("🏓", "탁구 라켓과 공", parsedData[[j]])
  parsedData[[j]] <- gsub("🏸", "배드민턴 라켓과 셔틀콕", parsedData[[j]])
  parsedData[[j]] <- gsub("🥅", "골망", parsedData[[j]])
  parsedData[[j]] <- gsub("🏒", "아이스하키 스틱과 퍽", parsedData[[j]])
  parsedData[[j]] <- gsub("🏑", "필드하키 스틱과 공", parsedData[[j]])
  parsedData[[j]] <- gsub("🏏", "크리켓 방망이와 공", parsedData[[j]])
  parsedData[[j]] <- gsub("⛳", "골프 홀에 있는 깃발", parsedData[[j]])
  parsedData[[j]] <- gsub("🏹", "활과 화살", parsedData[[j]])
  parsedData[[j]] <- gsub("🎣", "낚싯대와 물고기", parsedData[[j]])
  parsedData[[j]] <- gsub("🥊", "권투 글러브", parsedData[[j]])
  parsedData[[j]] <- gsub("🥋", "도복", parsedData[[j]])
  parsedData[[j]] <- gsub("⛸", "아이스 스케이트", parsedData[[j]])
  parsedData[[j]] <- gsub("🎿", "스키와 스키 부츠", parsedData[[j]])
  parsedData[[j]] <- gsub("⛷", "스키 타는 사람", parsedData[[j]])
  parsedData[[j]] <- gsub("🏂", "스노보드를 타는 사람", parsedData[[j]])
  parsedData[[j]] <- gsub("🤺", "펜싱 선수", parsedData[[j]])
  parsedData[[j]] <- gsub("🎽", "띠를 두른 셔츠", parsedData[[j]])
  parsedData[[j]] <- gsub("🎖", "군대 훈장", parsedData[[j]])
  parsedData[[j]] <- gsub("🏅", "스포츠 메달", parsedData[[j]])
  parsedData[[j]] <- gsub("🥇", "금메달", parsedData[[j]])
  parsedData[[j]] <- gsub("🥈", "은메달", parsedData[[j]])
  parsedData[[j]] <- gsub("🥉", "동메달", parsedData[[j]])
  parsedData[[j]] <- gsub("🏆", "트로피", parsedData[[j]])
  parsedData[[j]] <- gsub("🏵", "장미 모양 장식", parsedData[[j]])
  parsedData[[j]] <- gsub("🎗", "알림 리본", parsedData[[j]])
  parsedData[[j]] <- gsub("🎫", "입장권", parsedData[[j]])
  parsedData[[j]] <- gsub("🎟", "입장권", parsedData[[j]])
  parsedData[[j]] <- gsub("🎪", "서커스 천막", parsedData[[j]])
  parsedData[[j]] <- gsub("🎭", "공연", parsedData[[j]])
  parsedData[[j]] <- gsub("🎨", "그림 팔레트", parsedData[[j]])
  parsedData[[j]] <- gsub("🎬", "클래퍼 보드", parsedData[[j]])
  parsedData[[j]] <- gsub("🎤", "마이크", parsedData[[j]])
  parsedData[[j]] <- gsub("🎧", "헤드폰", parsedData[[j]])
  parsedData[[j]] <- gsub("🎼", "악보", parsedData[[j]])
  parsedData[[j]] <- gsub("🎹", "건반", parsedData[[j]])
  parsedData[[j]] <- gsub("🥁", "드럼과 드럼 스틱", parsedData[[j]])
  parsedData[[j]] <- gsub("🎷", "색소폰", parsedData[[j]])
  parsedData[[j]] <- gsub("🎺", "트럼펫", parsedData[[j]])
  parsedData[[j]] <- gsub("🎸", "기타", parsedData[[j]])
  parsedData[[j]] <- gsub("🎻", "바이올린", parsedData[[j]])
  parsedData[[j]] <- gsub("🎲", "주사위", parsedData[[j]])
  parsedData[[j]] <- gsub("🎯", "명중", parsedData[[j]])
  parsedData[[j]] <- gsub("🎳", "볼링", parsedData[[j]])
  parsedData[[j]] <- gsub("🎮", "비디오 게임", parsedData[[j]])
  parsedData[[j]] <- gsub("👾", "우주 괴물", parsedData[[j]])
  parsedData[[j]] <- gsub("🎰", "슬롯머신", parsedData[[j]])
}
# 7. Travel & Places Emojis
for (j in seq(parsedData)) {
  parsedData[[j]] <- gsub("🚗", "자동차", parsedData[[j]])
  parsedData[[j]] <- gsub("🚕", "택시", parsedData[[j]])
  parsedData[[j]] <- gsub("🚙", "SUV", parsedData[[j]])
  parsedData[[j]] <- gsub("🚌", "버스", parsedData[[j]])
  parsedData[[j]] <- gsub("🚎", "트롤리버스", parsedData[[j]])
  parsedData[[j]] <- gsub("🏎", "경주용 차", parsedData[[j]])
  parsedData[[j]] <- gsub("🚓", "경찰차", parsedData[[j]])
  parsedData[[j]] <- gsub("🚑", "구급차", parsedData[[j]])
  parsedData[[j]] <- gsub("🚒", "소방차", parsedData[[j]])
  parsedData[[j]] <- gsub("🚐", "미니버스", parsedData[[j]])
  parsedData[[j]] <- gsub("🚚", "배달 트럭", parsedData[[j]])
  parsedData[[j]] <- gsub("🚛", "트레일러", parsedData[[j]])
  parsedData[[j]] <- gsub("🚜", "트랙터", parsedData[[j]])
  parsedData[[j]] <- gsub("🏍", "경주용 오토바이", parsedData[[j]])
  parsedData[[j]] <- gsub("🛵", "모터 스쿠터", parsedData[[j]])
  parsedData[[j]] <- gsub("🚲", "자전거", parsedData[[j]])
  parsedData[[j]] <- gsub("🛴", "스쿠터", parsedData[[j]])
  parsedData[[j]] <- gsub("🚨", "경찰차 사이렌", parsedData[[j]])
  parsedData[[j]] <- gsub("🚔", "다가오는 경찰차", parsedData[[j]])
  parsedData[[j]] <- gsub("🚍", "다가오는 버스", parsedData[[j]])
  parsedData[[j]] <- gsub("🚘", "다가오는 자동차", parsedData[[j]])
  parsedData[[j]] <- gsub("🚖", "다가오는 택시", parsedData[[j]])
  parsedData[[j]] <- gsub("🚡", "공중 케이블카", parsedData[[j]])
  parsedData[[j]] <- gsub("🚠", "산악용 케이블카", parsedData[[j]])
  parsedData[[j]] <- gsub("🚟", "케이블카", parsedData[[j]])
  parsedData[[j]] <- gsub("🚃", "철도 차량", parsedData[[j]])
  parsedData[[j]] <- gsub("🚋", "전차 차량", parsedData[[j]])
  parsedData[[j]] <- gsub("🚝", "모노레일", parsedData[[j]])
  parsedData[[j]] <- gsub("🚄", "고속 열차", parsedData[[j]])
  parsedData[[j]] <- gsub("🚅", "고속 탄환 열차", parsedData[[j]])
  parsedData[[j]] <- gsub("🚈", "경전철", parsedData[[j]])
  parsedData[[j]] <- gsub("🚞", "산악 기차", parsedData[[j]])
  parsedData[[j]] <- gsub("🚂", "증기 기관차", parsedData[[j]])
  parsedData[[j]] <- gsub("🚆", "기차", parsedData[[j]])
  parsedData[[j]] <- gsub("🚇", "지하철", parsedData[[j]])
  parsedData[[j]] <- gsub("🚊", "전차", parsedData[[j]])
  parsedData[[j]] <- gsub("🚉", "역", parsedData[[j]])
  parsedData[[j]] <- gsub("🚁", "헬리콥터", parsedData[[j]])
  parsedData[[j]] <- gsub("🛩", "소형 비행기", parsedData[[j]])
  parsedData[[j]] <- gsub("✈", "비행기", parsedData[[j]])
  parsedData[[j]] <- gsub("🛫", "비행기 출발", parsedData[[j]])
  parsedData[[j]] <- gsub("🛬", "비행기 도착", parsedData[[j]])
  parsedData[[j]] <- gsub("🛶", "카누", parsedData[[j]])
  parsedData[[j]] <- gsub("⛵", "범선", parsedData[[j]])
  parsedData[[j]] <- gsub("🛥", "모터보트", parsedData[[j]])
  parsedData[[j]] <- gsub("🚤", "모터보트", parsedData[[j]])
  parsedData[[j]] <- gsub("⛴", "페리", parsedData[[j]])
  parsedData[[j]] <- gsub("🛳", "여객선", parsedData[[j]])
  parsedData[[j]] <- gsub("🚀", "로켓", parsedData[[j]])
  parsedData[[j]] <- gsub("🛰", "인공위성", parsedData[[j]])
  parsedData[[j]] <- gsub("💺", "좌석", parsedData[[j]])
  parsedData[[j]] <- gsub("⚓", "닻", parsedData[[j]])
  parsedData[[j]] <- gsub("🚧", "공사 표지", parsedData[[j]])
  parsedData[[j]] <- gsub("⛽", "주유기", parsedData[[j]])
  parsedData[[j]] <- gsub("🚏", "버스 정류장", parsedData[[j]])
  parsedData[[j]] <- gsub("🚦", "세로 신호등", parsedData[[j]])
  parsedData[[j]] <- gsub("🚥", "가로 신호등", parsedData[[j]])
  parsedData[[j]] <- gsub("🛑", "팔각형 표지", parsedData[[j]])
  parsedData[[j]] <- gsub("🚢", "배", parsedData[[j]])
  parsedData[[j]] <- gsub("🎡", "관람차", parsedData[[j]])
  parsedData[[j]] <- gsub("🎢", "롤러코스터", parsedData[[j]])
  parsedData[[j]] <- gsub("🎠", "회전목마", parsedData[[j]])
  parsedData[[j]] <- gsub("🏗", "건물 건축", parsedData[[j]])
  parsedData[[j]] <- gsub("🌁", "안개", parsedData[[j]])
  parsedData[[j]] <- gsub("🗼", "도쿄 타워", parsedData[[j]])
  parsedData[[j]] <- gsub("🏭", "공장", parsedData[[j]])
  parsedData[[j]] <- gsub("⛲", "분수", parsedData[[j]])
  parsedData[[j]] <- gsub("🎑", "달맞이 행사", parsedData[[j]])
  parsedData[[j]] <- gsub("⛰", "산", parsedData[[j]])
  parsedData[[j]] <- gsub("🏔", "눈 덮인 산", parsedData[[j]])
  parsedData[[j]] <- gsub("🗻", "후지 산", parsedData[[j]])
  parsedData[[j]] <- gsub("🌋", "화산", parsedData[[j]])
  parsedData[[j]] <- gsub("🗾", "일본의 실루엣", parsedData[[j]])
  parsedData[[j]] <- gsub("🏕", "캠핑", parsedData[[j]])
  parsedData[[j]] <- gsub("⛺", "텐트", parsedData[[j]])
  parsedData[[j]] <- gsub("🏞", "국립공원", parsedData[[j]])
  parsedData[[j]] <- gsub("🛣", "자동차용 도로", parsedData[[j]])
  parsedData[[j]] <- gsub("🛤", "철로", parsedData[[j]])
  parsedData[[j]] <- gsub("🌅", "일출", parsedData[[j]])
  parsedData[[j]] <- gsub("🌄", "산 위의 일출", parsedData[[j]])
  parsedData[[j]] <- gsub("🏜", "사막", parsedData[[j]])
  parsedData[[j]] <- gsub("🏖", "우산이 있는 해변", parsedData[[j]])
  parsedData[[j]] <- gsub("🏝", "사막 섬", parsedData[[j]])
  parsedData[[j]] <- gsub("🌇", "빌딩 너머로 지는 해", parsedData[[j]])
  parsedData[[j]] <- gsub("🌆", "황혼녘 도시 전경", parsedData[[j]])
  parsedData[[j]] <- gsub("🏙", "도시 풍경", parsedData[[j]])
  parsedData[[j]] <- gsub("🌃", "별 밤", parsedData[[j]])
  parsedData[[j]] <- gsub("🌉", "교량 야경", parsedData[[j]])
  parsedData[[j]] <- gsub("🌌", "은하수", parsedData[[j]])
  parsedData[[j]] <- gsub("🌠", "별똥별", parsedData[[j]])
  parsedData[[j]] <- gsub("🎇", "불꽃놀이 폭죽", parsedData[[j]])
  parsedData[[j]] <- gsub("🎆", "불꽃놀이", parsedData[[j]])
  parsedData[[j]] <- gsub("🌈", "무지개", parsedData[[j]])
  parsedData[[j]] <- gsub("🏘", "주택 건물", parsedData[[j]])
  parsedData[[j]] <- gsub("🏰", "유럽 성", parsedData[[j]])
  parsedData[[j]] <- gsub("🏯", "일본 성", parsedData[[j]])
  parsedData[[j]] <- gsub("🏟", "경기장", parsedData[[j]])
  parsedData[[j]] <- gsub("🗽", "자유의 여신상", parsedData[[j]])
  parsedData[[j]] <- gsub("🏠", "주택", parsedData[[j]])
  parsedData[[j]] <- gsub("🏡", "뜰이 있는 집", parsedData[[j]])
  parsedData[[j]] <- gsub("🏚", "버려진 주택 건물", parsedData[[j]])
  parsedData[[j]] <- gsub("🏢", "사무실 건물", parsedData[[j]])
  parsedData[[j]] <- gsub("🏬", "백화점", parsedData[[j]])
  parsedData[[j]] <- gsub("🏣", "일본 우체국", parsedData[[j]])
  parsedData[[j]] <- gsub("🏤", "유럽 우체국", parsedData[[j]])
  parsedData[[j]] <- gsub("🏥", "병원", parsedData[[j]])
  parsedData[[j]] <- gsub("🏦", "은행", parsedData[[j]])
  parsedData[[j]] <- gsub("🏨", "호텔", parsedData[[j]])
  parsedData[[j]] <- gsub("🏪", "편의점", parsedData[[j]])
  parsedData[[j]] <- gsub("🏫", "학교", parsedData[[j]])
  parsedData[[j]] <- gsub("🏩", "러브호텔", parsedData[[j]])
  parsedData[[j]] <- gsub("💒", "결혼", parsedData[[j]])
  parsedData[[j]] <- gsub("🏛", "고전 양식 건물", parsedData[[j]])
  parsedData[[j]] <- gsub("⛪", "교회", parsedData[[j]])
  parsedData[[j]] <- gsub("🕌", "모스크", parsedData[[j]])
  parsedData[[j]] <- gsub("🕍", "유대교 회당", parsedData[[j]])
  parsedData[[j]] <- gsub("🕋", "카바신전", parsedData[[j]])
  parsedData[[j]] <- gsub("⛩", "신사", parsedData[[j]])
}
# 8. Objects Emojis
for (j in seq(parsedData)) {
  parsedData[[j]] <- gsub("⌚", "손목시계", parsedData[[j]])
  parsedData[[j]] <- gsub("📱", "휴대전화", parsedData[[j]])
  parsedData[[j]] <- gsub("📲", "오른쪽 화살표가 왼쪽에 있는 휴대전화", parsedData[[j]])
  parsedData[[j]] <- gsub("💻", "개인 컴퓨터", parsedData[[j]])
  parsedData[[j]] <- gsub("⌨", "키보드", parsedData[[j]])
  parsedData[[j]] <- gsub("🖥", "데스크톱 컴퓨터", parsedData[[j]])
  parsedData[[j]] <- gsub("🖨", "프린터", parsedData[[j]])
  parsedData[[j]] <- gsub("🖱", "3버튼 마우스", parsedData[[j]])
  parsedData[[j]] <- gsub("🖲", "트랙볼", parsedData[[j]])
  parsedData[[j]] <- gsub("🕹", "조이스틱", parsedData[[j]])
  parsedData[[j]] <- gsub("🗜", "압축", parsedData[[j]])
  parsedData[[j]] <- gsub("💽", "미니 디스크", parsedData[[j]])
  parsedData[[j]] <- gsub("💾", "플로피 디스크", parsedData[[j]])
  parsedData[[j]] <- gsub("💿", "광학 디스크", parsedData[[j]])
  parsedData[[j]] <- gsub("📀", "DVD", parsedData[[j]])
  parsedData[[j]] <- gsub("📼", "비디오 카세트", parsedData[[j]])
  parsedData[[j]] <- gsub("📷", "카메라", parsedData[[j]])
  parsedData[[j]] <- gsub("📸", "플래시가 있는 카메라", parsedData[[j]])
  parsedData[[j]] <- gsub("📹", "비디오 카메라", parsedData[[j]])
  parsedData[[j]] <- gsub("🎥", "영화 카메라", parsedData[[j]])
  parsedData[[j]] <- gsub("📽", "필름 영사기", parsedData[[j]])
  parsedData[[j]] <- gsub("🎞", "필름 틀", parsedData[[j]])
  parsedData[[j]] <- gsub("📞", "전화 수화기", parsedData[[j]])
  parsedData[[j]] <- gsub("☎", "검은색 전화기", parsedData[[j]])
  parsedData[[j]] <- gsub("📟", "호출기", parsedData[[j]])
  parsedData[[j]] <- gsub("📠", "팩스기", parsedData[[j]])
  parsedData[[j]] <- gsub("📺", "텔레비전", parsedData[[j]])
  parsedData[[j]] <- gsub("📻", "라디오", parsedData[[j]])
  parsedData[[j]] <- gsub("🎙", "스튜디오 마이크", parsedData[[j]])
  parsedData[[j]] <- gsub("🎚", "레벨 조절 슬라이더", parsedData[[j]])
  parsedData[[j]] <- gsub("🎛", "제어 손잡이", parsedData[[j]])
  parsedData[[j]] <- gsub("⏱", "스톱워치", parsedData[[j]])
  parsedData[[j]] <- gsub("⏲", "타이머 시계", parsedData[[j]])
  parsedData[[j]] <- gsub("⏰", "알람 시계", parsedData[[j]])
  parsedData[[j]] <- gsub("🕰", "선반 시계", parsedData[[j]])
  parsedData[[j]] <- gsub("⏳", "모래가 떨어지는 모래시계", parsedData[[j]])
  parsedData[[j]] <- gsub("⌛", "모래시계", parsedData[[j]])
  parsedData[[j]] <- gsub("📡", "위성 안테나", parsedData[[j]])
  parsedData[[j]] <- gsub("🔋", "배터리", parsedData[[j]])
  parsedData[[j]] <- gsub("🔌", "전기 플러그", parsedData[[j]])
  parsedData[[j]] <- gsub("💡", "전구", parsedData[[j]])
  parsedData[[j]] <- gsub("🔦", "손전등", parsedData[[j]])
  parsedData[[j]] <- gsub("🕯", "양초", parsedData[[j]])
  parsedData[[j]] <- gsub("🗑", "휴지통", parsedData[[j]])
  parsedData[[j]] <- gsub("🛢", "기름통", parsedData[[j]])
  parsedData[[j]] <- gsub("🛒", "쇼핑 카트", parsedData[[j]])
  parsedData[[j]] <- gsub("💸", "날개 달린 돈다발", parsedData[[j]])
  parsedData[[j]] <- gsub("💵", "달러 지폐", parsedData[[j]])
  parsedData[[j]] <- gsub("💴", "엔화 지폐", parsedData[[j]])
  parsedData[[j]] <- gsub("💶", "유로화 지폐", parsedData[[j]])
  parsedData[[j]] <- gsub("💷", "파운드화 지폐", parsedData[[j]])
  parsedData[[j]] <- gsub("💰", "돈 가방", parsedData[[j]])
  parsedData[[j]] <- gsub("💳", "신용카드", parsedData[[j]])
  parsedData[[j]] <- gsub("💎", "보석", parsedData[[j]])
  parsedData[[j]] <- gsub("⚖", "저울", parsedData[[j]])
  parsedData[[j]] <- gsub("🔧", "렌치", parsedData[[j]])
  parsedData[[j]] <- gsub("🔨", "망치", parsedData[[j]])
  parsedData[[j]] <- gsub("⚒", "망치와 곡괭이", parsedData[[j]])
  parsedData[[j]] <- gsub("🛠", "망치와 렌치", parsedData[[j]])
  parsedData[[j]] <- gsub("⛏", "곡괭이", parsedData[[j]])
  parsedData[[j]] <- gsub("🔩", "너트와 볼트", parsedData[[j]])
  parsedData[[j]] <- gsub("⚙", "기어", parsedData[[j]])
  parsedData[[j]] <- gsub("⛓", "사슬", parsedData[[j]])
  parsedData[[j]] <- gsub("🔫", "권총", parsedData[[j]])
  parsedData[[j]] <- gsub("💣", "폭탄", parsedData[[j]])
  parsedData[[j]] <- gsub("🔪", "식칼", parsedData[[j]])
  parsedData[[j]] <- gsub("🗡", "단검", parsedData[[j]])
  parsedData[[j]] <- gsub("⚔", "교차된 검", parsedData[[j]])
  parsedData[[j]] <- gsub("🛡", "방패", parsedData[[j]])
  parsedData[[j]] <- gsub("🚬", "흡연 기호", parsedData[[j]])
  parsedData[[j]] <- gsub("⚰", "관", parsedData[[j]])
  parsedData[[j]] <- gsub("⚱", "유골 단지", parsedData[[j]])
  parsedData[[j]] <- gsub("🏺", "고대 항아리", parsedData[[j]])
  parsedData[[j]] <- gsub("🔮", "수정구", parsedData[[j]])
  parsedData[[j]] <- gsub("📿", "묵주", parsedData[[j]])
  parsedData[[j]] <- gsub("💈", "이발소의 간판 기둥", parsedData[[j]])
  parsedData[[j]] <- gsub("⚗", "증류기", parsedData[[j]])
  parsedData[[j]] <- gsub("🔭", "망원경", parsedData[[j]])
  parsedData[[j]] <- gsub("🔬", "현미경", parsedData[[j]])
  parsedData[[j]] <- gsub("🕳", "구멍", parsedData[[j]])
  parsedData[[j]] <- gsub("💊", "알약", parsedData[[j]])
  parsedData[[j]] <- gsub("💉", "주사기", parsedData[[j]])
  parsedData[[j]] <- gsub("🌡", "온도계", parsedData[[j]])
  parsedData[[j]] <- gsub("🏷", "라벨", parsedData[[j]])
  parsedData[[j]] <- gsub("🔖", "책갈피", parsedData[[j]])
  parsedData[[j]] <- gsub("🚽", "변기", parsedData[[j]])
  parsedData[[j]] <- gsub("🚿", "샤워", parsedData[[j]])
  parsedData[[j]] <- gsub("🛁", "욕조", parsedData[[j]])
  parsedData[[j]] <- gsub("🛀", "목욕", parsedData[[j]])
  parsedData[[j]] <- gsub("🔑", "열쇠", parsedData[[j]])
  parsedData[[j]] <- gsub("🗝", "오래된 열쇠", parsedData[[j]])
  parsedData[[j]] <- gsub("🛋", "소파와 램프", parsedData[[j]])
  parsedData[[j]] <- gsub("🛌", "숙박 시설", parsedData[[j]])
  parsedData[[j]] <- gsub("🛏", "침대", parsedData[[j]])
  parsedData[[j]] <- gsub("🚪", "문", parsedData[[j]])
  parsedData[[j]] <- gsub("🛎", "호출 벨", parsedData[[j]])
  parsedData[[j]] <- gsub("🖼", "사진이 있는 액자", parsedData[[j]])
  parsedData[[j]] <- gsub("🗺", "세계 지도", parsedData[[j]])
  parsedData[[j]] <- gsub("⛱", "땅에 놓인 우산", parsedData[[j]])
  parsedData[[j]] <- gsub("🗿", "모아의 석상", parsedData[[j]])
  parsedData[[j]] <- gsub("🛍", "쇼핑백", parsedData[[j]])
  parsedData[[j]] <- gsub("🎈", "풍선", parsedData[[j]])
  parsedData[[j]] <- gsub("🎏", "잉어 모양 깃발", parsedData[[j]])
  parsedData[[j]] <- gsub("🎀", "리본", parsedData[[j]])
  parsedData[[j]] <- gsub("🎁", "포장된 선물", parsedData[[j]])
  parsedData[[j]] <- gsub("🎊", "박 터트리기", parsedData[[j]])
  parsedData[[j]] <- gsub("🎉", "파티 폭죽", parsedData[[j]])
  parsedData[[j]] <- gsub("🎎", "일본 인형", parsedData[[j]])
  parsedData[[j]] <- gsub("🎐", "풍경", parsedData[[j]])
  parsedData[[j]] <- gsub("🏮", "주점 초롱", parsedData[[j]])
  parsedData[[j]] <- gsub("✉", "봉투", parsedData[[j]])
  parsedData[[j]] <- gsub("📩", "아래 화살표가 위에 있는 봉투", parsedData[[j]])
  parsedData[[j]] <- gsub("📨", "수신 메시지 봉투", parsedData[[j]])
  parsedData[[j]] <- gsub("📧", "이메일 기호", parsedData[[j]])
  parsedData[[j]] <- gsub("💌", "연애편지", parsedData[[j]])
  parsedData[[j]] <- gsub("📮", "우체통", parsedData[[j]])
  parsedData[[j]] <- gsub("📪", "깃발을 내리고 닫혀 있는 우편함", parsedData[[j]])
  parsedData[[j]] <- gsub("📫", "깃발을 올리고 닫혀 있는 우편함", parsedData[[j]])
  parsedData[[j]] <- gsub("📬", "깃발을 올리고 열려 있는 우편함", parsedData[[j]])
  parsedData[[j]] <- gsub("📭", "깃발을 내리고 열려 있는 우편함", parsedData[[j]])
  parsedData[[j]] <- gsub("📦", "소포", parsedData[[j]])
  parsedData[[j]] <- gsub("📯", "나팔", parsedData[[j]])
  parsedData[[j]] <- gsub("📥", "받은 편지함 트레이", parsedData[[j]])
  parsedData[[j]] <- gsub("📤", "보낼 편지함 트레이", parsedData[[j]])
  parsedData[[j]] <- gsub("📜", "두루마리", parsedData[[j]])
  parsedData[[j]] <- gsub("📃", "끝이 둥글게 말린 종이", parsedData[[j]])
  parsedData[[j]] <- gsub("📑", "즐겨찾기 탭", parsedData[[j]])
  parsedData[[j]] <- gsub("📊", "막대그래프", parsedData[[j]])
  parsedData[[j]] <- gsub("📈", "상향 추세의 차트", parsedData[[j]])
  parsedData[[j]] <- gsub("📉", "하향 추세의 차트", parsedData[[j]])
  parsedData[[j]] <- gsub("📄", "종이 앞면", parsedData[[j]])
  parsedData[[j]] <- gsub("📅", "달력", parsedData[[j]])
  parsedData[[j]] <- gsub("📆", "일일달력", parsedData[[j]])
  parsedData[[j]] <- gsub("🗓", "스프링 달력", parsedData[[j]])
  parsedData[[j]] <- gsub("📇", "카드 색인 바인더", parsedData[[j]])
  parsedData[[j]] <- gsub("🗃", "카드 파일 상자", parsedData[[j]])
  parsedData[[j]] <- gsub("🗳", "투표 용지와 투표함", parsedData[[j]])
  parsedData[[j]] <- gsub("🗄", "파일 캐비닛", parsedData[[j]])
  parsedData[[j]] <- gsub("📋", "클립보드", parsedData[[j]])
  parsedData[[j]] <- gsub("🗒", "스프링 메모장", parsedData[[j]])
  parsedData[[j]] <- gsub("📁", "파일 폴더", parsedData[[j]])
  parsedData[[j]] <- gsub("📂", "열려있는 파일 폴더", parsedData[[j]])
  parsedData[[j]] <- gsub("🗂", "카드 색인 디바이더", parsedData[[j]])
  parsedData[[j]] <- gsub("🗞", "말려진 신문", parsedData[[j]])
  parsedData[[j]] <- gsub("📰", "신문", parsedData[[j]])
  parsedData[[j]] <- gsub("📓", "공책", parsedData[[j]])
  parsedData[[j]] <- gsub("📕", "덮인 책", parsedData[[j]])
  parsedData[[j]] <- gsub("📗", "녹색 책", parsedData[[j]])
  parsedData[[j]] <- gsub("📘", "파란색 책", parsedData[[j]])
  parsedData[[j]] <- gsub("📙", "주황색 책", parsedData[[j]])
  parsedData[[j]] <- gsub("📔", "장식 표지가 있는 공책", parsedData[[j]])
  parsedData[[j]] <- gsub("📒", "원장", parsedData[[j]])
  parsedData[[j]] <- gsub("📚", "여러 권의 책", parsedData[[j]])
  parsedData[[j]] <- gsub("📖", "펼친 책", parsedData[[j]])
  parsedData[[j]] <- gsub("🔗", "사슬 기호", parsedData[[j]])
  parsedData[[j]] <- gsub("📎", "클립", parsedData[[j]])
  parsedData[[j]] <- gsub("🖇", "연결된 클립", parsedData[[j]])
  parsedData[[j]] <- gsub("✂", "검은색 가위", parsedData[[j]])
  parsedData[[j]] <- gsub("📐", "삼각자", parsedData[[j]])
  parsedData[[j]] <- gsub("📏", "막대자", parsedData[[j]])
  parsedData[[j]] <- gsub("📌", "압정", parsedData[[j]])
  parsedData[[j]] <- gsub("📍", "둥근 압정", parsedData[[j]])
  parsedData[[j]] <- gsub("🔐", "열쇠와 자물쇠", parsedData[[j]])
  parsedData[[j]] <- gsub("🔒", "자물쇠", parsedData[[j]])
  parsedData[[j]] <- gsub("🔓", "열려있는 자물쇠", parsedData[[j]])
  parsedData[[j]] <- gsub("🔏", "잉크 펜과 자물쇠", parsedData[[j]])
  parsedData[[j]] <- gsub("🖊", "왼쪽 아래를 향한 볼펜", parsedData[[j]])
  parsedData[[j]] <- gsub("🖋", "왼쪽 아래를 향한 만년필", parsedData[[j]])
  parsedData[[j]] <- gsub("✒", "검은색 펜촉", parsedData[[j]])
  parsedData[[j]] <- gsub("📝", "메모", parsedData[[j]])
  parsedData[[j]] <- gsub("✏", "연필", parsedData[[j]])
  parsedData[[j]] <- gsub("🖍", "왼쪽 아래를 향한 크레용", parsedData[[j]])
  parsedData[[j]] <- gsub("🖌", "왼쪽 아래를 향한 붓", parsedData[[j]])
  parsedData[[j]] <- gsub("🔍", "왼쪽을 향한 돋보기", parsedData[[j]])
  parsedData[[j]] <- gsub("🔎", "오른쪽을 향한 돋보기", parsedData[[j]])
}
# 9. Symbols Emojis
for (j in seq(parsedData)) {
  parsedData[[j]] <- gsub("❤", "검은색 하트", parsedData[[j]])
  parsedData[[j]] <- gsub("💛", "노란색 하트", parsedData[[j]])
  parsedData[[j]] <- gsub("💚", "녹색 하트", parsedData[[j]])
  parsedData[[j]] <- gsub("💙", "파란색 하트", parsedData[[j]])
  parsedData[[j]] <- gsub("💜", "보라색 하트", parsedData[[j]])
  parsedData[[j]] <- gsub("🖤", "검정색 하트", parsedData[[j]])
  parsedData[[j]] <- gsub("💔", "깨진 하트", parsedData[[j]])
  parsedData[[j]] <- gsub("❣", "두꺼운 하트 느낌표 장식", parsedData[[j]])
  parsedData[[j]] <- gsub("💕", "두 개의 하트", parsedData[[j]])
  parsedData[[j]] <- gsub("💞", "회전하는 하트", parsedData[[j]])
  parsedData[[j]] <- gsub("💓", "두근거리는 하트", parsedData[[j]])
  parsedData[[j]] <- gsub("💗", "점점 커지는 하트", parsedData[[j]])
  parsedData[[j]] <- gsub("💖", "반짝이는 하트", parsedData[[j]])
  parsedData[[j]] <- gsub("💘", "화살 맞은 하트", parsedData[[j]])
  parsedData[[j]] <- gsub("💝", "리본 달린 하트", parsedData[[j]])
  parsedData[[j]] <- gsub("💟", "하트 장식", parsedData[[j]])
  parsedData[[j]] <- gsub("☮", "평화 기호", parsedData[[j]])
  parsedData[[j]] <- gsub("✝", "라틴 십자가", parsedData[[j]])
  parsedData[[j]] <- gsub("☪", "별과 초승달", parsedData[[j]])
  parsedData[[j]] <- gsub("🕉", "옴 기호", parsedData[[j]])
  parsedData[[j]] <- gsub("☸", "법륜", parsedData[[j]])
  parsedData[[j]] <- gsub("✡", "다윗의 별", parsedData[[j]])
  parsedData[[j]] <- gsub("🔯", "중앙에 점이 있고 6각별", parsedData[[j]])
  parsedData[[j]] <- gsub("🕎", "아홉 갈래로 나뉜 메노라", parsedData[[j]])
  parsedData[[j]] <- gsub("☯", "음양", parsedData[[j]])
  parsedData[[j]] <- gsub("☦", "동방 정교회 십자가", parsedData[[j]])
  parsedData[[j]] <- gsub("🛐", "예배 장소", parsedData[[j]])
  parsedData[[j]] <- gsub("⛎", "뱀주인자리", parsedData[[j]])
  parsedData[[j]] <- gsub("♈", "양자리", parsedData[[j]])
  parsedData[[j]] <- gsub("♉", "황소자리", parsedData[[j]])
  parsedData[[j]] <- gsub("♊", "쌍둥이자리", parsedData[[j]])
  parsedData[[j]] <- gsub("♋", "게자리", parsedData[[j]])
  parsedData[[j]] <- gsub("♌", "사자자리", parsedData[[j]])
  parsedData[[j]] <- gsub("♍", "처녀자리", parsedData[[j]])
  parsedData[[j]] <- gsub("♎", "천칭자리", parsedData[[j]])
  parsedData[[j]] <- gsub("♏", "전갈자리", parsedData[[j]])
  parsedData[[j]] <- gsub("♐", "궁수자리", parsedData[[j]])
  parsedData[[j]] <- gsub("♑", "염소자리", parsedData[[j]])
  parsedData[[j]] <- gsub("♒", "물병자리", parsedData[[j]])
  parsedData[[j]] <- gsub("♓", "물고기자리", parsedData[[j]])
  parsedData[[j]] <- gsub("🆔", "ID 블록", parsedData[[j]])
  parsedData[[j]] <- gsub("⚛", "원자 기호", parsedData[[j]])
  parsedData[[j]] <- gsub("⚕", "아이스쿨라피우스의 지팡이", parsedData[[j]])
  parsedData[[j]] <- gsub("☢", "방사능 기호", parsedData[[j]])
  parsedData[[j]] <- gsub("☣", "생물학적 위험 기호", parsedData[[j]])
  parsedData[[j]] <- gsub("📴", "휴대전화 끄기", parsedData[[j]])
  parsedData[[j]] <- gsub("📳", "진동 모드", parsedData[[j]])
  parsedData[[j]] <- gsub("🈶", "한자 표기 유료 블록", parsedData[[j]])
  parsedData[[j]] <- gsub("🈚", "한자 표기 무료 블록", parsedData[[j]])
  parsedData[[j]] <- gsub("🈸", "한자 표기 적용 블록", parsedData[[j]])
  parsedData[[j]] <- gsub("🈺", "한자 표기 영업 중 블록", parsedData[[j]])
  parsedData[[j]] <- gsub("🈷", "한자 표기 월 블록", parsedData[[j]])
  parsedData[[j]] <- gsub("✴", "8각 검은 별", parsedData[[j]])
  parsedData[[j]] <- gsub("🆚", "VS 블록", parsedData[[j]])
  parsedData[[j]] <- gsub("🉑", "한자 표기 수락 원문자", parsedData[[j]])
  parsedData[[j]] <- gsub("💮", "흰색 꽃", parsedData[[j]])
  parsedData[[j]] <- gsub("🉐", "한자 표기 이익 원문자", parsedData[[j]])
  parsedData[[j]] <- gsub("㊙", "한자 표기 비밀 원문자", parsedData[[j]])
  parsedData[[j]] <- gsub("㊗", "한자 표기 축하 원문자", parsedData[[j]])
  parsedData[[j]] <- gsub("🈴", "한자 표기 수락 블록", parsedData[[j]])
  parsedData[[j]] <- gsub("🈵", "한자 표기 빈자리 없음 블록", parsedData[[j]])
  parsedData[[j]] <- gsub("🈹", "한자 표기 할인 블록", parsedData[[j]])
  parsedData[[j]] <- gsub("🈲", "한자 표기 금지 블록", parsedData[[j]])
  parsedData[[j]] <- gsub("🆎", "혈액형 AB", parsedData[[j]])
  parsedData[[j]] <- gsub("🆑", "CL 블록", parsedData[[j]])
  parsedData[[j]] <- gsub("🆘", "SOS 블록", parsedData[[j]])
  parsedData[[j]] <- gsub("⛔", "진입 금지", parsedData[[j]])
  parsedData[[j]] <- gsub("📛", "명찰", parsedData[[j]])
  parsedData[[j]] <- gsub("🚫", "출입 금지 기호", parsedData[[j]])
  parsedData[[j]] <- gsub("❌", "곱셈 표시", parsedData[[j]])
  parsedData[[j]] <- gsub("⭕", "굵은 선으로 된 흰색 원", parsedData[[j]])
  parsedData[[j]] <- gsub("💢", "분노 기호", parsedData[[j]])
  parsedData[[j]] <- gsub("♨", "온천", parsedData[[j]])
  parsedData[[j]] <- gsub("🚷", "보행 금지", parsedData[[j]])
  parsedData[[j]] <- gsub("🚯", "쓰레기 무단 투기 금지 기호", parsedData[[j]])
  parsedData[[j]] <- gsub("🚳", "자전거 금지", parsedData[[j]])
  parsedData[[j]] <- gsub("🚱", "식수 금지 기호", parsedData[[j]])
  parsedData[[j]] <- gsub("🔞", "18세 이하 금지 기호", parsedData[[j]])
  parsedData[[j]] <- gsub("📵", "휴대전화 사용 금지", parsedData[[j]])
  parsedData[[j]] <- gsub("🚭", "금연 기호", parsedData[[j]])
  parsedData[[j]] <- gsub("❗", "굵은 느낌표 기호", parsedData[[j]])
  parsedData[[j]] <- gsub("❕", "흰색 느낌표", parsedData[[j]])
  parsedData[[j]] <- gsub("❓", "검은색 물음표", parsedData[[j]])
  parsedData[[j]] <- gsub("❔", "흰색 물음표", parsedData[[j]])
  parsedData[[j]] <- gsub("‼", "느낌표 2개", parsedData[[j]])
  parsedData[[j]] <- gsub("⁉", "느낌표 물음표", parsedData[[j]])
  parsedData[[j]] <- gsub("💯", "백점 기호", parsedData[[j]])
  parsedData[[j]] <- gsub("🔅", "낮은 명도 기호", parsedData[[j]])
  parsedData[[j]] <- gsub("🔆", "높은 명도 기호", parsedData[[j]])
  parsedData[[j]] <- gsub("🔱", "삼지창 엠블럼", parsedData[[j]])
  parsedData[[j]] <- gsub("⚜", "백합 문장", parsedData[[j]])
  parsedData[[j]] <- gsub("〽", "부품 교체 마크", parsedData[[j]])
  parsedData[[j]] <- gsub("🚸", "길 건너는 어린이", parsedData[[j]])
  parsedData[[j]] <- gsub("🔰", "일본식 초보자 기호", parsedData[[j]])
  parsedData[[j]] <- gsub("♻", "검은색 보편적인 재활용 기호", parsedData[[j]])
  parsedData[[j]] <- gsub("🈯", "한자 표기 예약석 블록", parsedData[[j]])
  parsedData[[j]] <- gsub("💹", "엔화 기호가 있는 상향 추세의 차트", parsedData[[j]])
  parsedData[[j]] <- gsub("❇", "광채", parsedData[[j]])
  parsedData[[j]] <- gsub("✳", "8각 별표", parsedData[[j]])
  parsedData[[j]] <- gsub("❎", "음각 곱셈 표시 블록", parsedData[[j]])
  parsedData[[j]] <- gsub("✅", "굵은 흰색 체크표시", parsedData[[j]])
  parsedData[[j]] <- gsub("💠", "내부에 점에 있는 마름모 도형", parsedData[[j]])
  parsedData[[j]] <- gsub("🌀", "태풍", parsedData[[j]])
  parsedData[[j]] <- gsub("➿", "두 번 꼬인 선", parsedData[[j]])
  parsedData[[j]] <- gsub("🌐", "자오선이 있는 지구본", parsedData[[j]])
  parsedData[[j]] <- gsub("Ⓜ", "라틴어 M 원문자", parsedData[[j]])
  parsedData[[j]] <- gsub("🏧", "ATM", parsedData[[j]])
  parsedData[[j]] <- gsub("🚾", "WC", parsedData[[j]])
  parsedData[[j]] <- gsub("♿", "휠체어 기호", parsedData[[j]])
  parsedData[[j]] <- gsub("🅿", "주차장", parsedData[[j]])
  parsedData[[j]] <- gsub("🈳", "한자 표기 빈자리 블록", parsedData[[j]])
  parsedData[[j]] <- gsub("🈂", "카타카나 서비스 블록", parsedData[[j]])
  parsedData[[j]] <- gsub("🛂", "출입국 관리", parsedData[[j]])
  parsedData[[j]] <- gsub("🛃", "세관", parsedData[[j]])
  parsedData[[j]] <- gsub("🛄", "수하물", parsedData[[j]])
  parsedData[[j]] <- gsub("🛅", "미수취 수하물", parsedData[[j]])
  parsedData[[j]] <- gsub("🚰", "식수 기호", parsedData[[j]])
  parsedData[[j]] <- gsub("🚹", "남자 기호", parsedData[[j]])
  parsedData[[j]] <- gsub("♂", "남성 기호", parsedData[[j]])
  parsedData[[j]] <- gsub("🚺", "여자 기호", parsedData[[j]])
  parsedData[[j]] <- gsub("♀", "여성 기호", parsedData[[j]])
  parsedData[[j]] <- gsub("🚼", "아기 기호", parsedData[[j]])
  parsedData[[j]] <- gsub("🚻", "화장실", parsedData[[j]])
  parsedData[[j]] <- gsub("🚮", "쓰레기통 사용 권장 기호", parsedData[[j]])
  parsedData[[j]] <- gsub("🎦", "극장", parsedData[[j]])
  parsedData[[j]] <- gsub("📶", "신호가 강한 안테나", parsedData[[j]])
  parsedData[[j]] <- gsub("🈁", "카타카나 여기 블록", parsedData[[j]])
  parsedData[[j]] <- gsub("🆖", "NG 블록", parsedData[[j]])
  parsedData[[j]] <- gsub("🆗", "OK 블록", parsedData[[j]])
  parsedData[[j]] <- gsub("🆙", "UP! 블록", parsedData[[j]])
  parsedData[[j]] <- gsub("🆒", "COOL 블록", parsedData[[j]])
  parsedData[[j]] <- gsub("🆕", "NEW 블록", parsedData[[j]])
  parsedData[[j]] <- gsub("🆓", "FREE 블록", parsedData[[j]])
  parsedData[[j]] <- gsub("0⃣", "키캡 숫자 0", parsedData[[j]])
  parsedData[[j]] <- gsub("1⃣", "키캡 숫자 1", parsedData[[j]])
  parsedData[[j]] <- gsub("2⃣", "키캡 숫자 2", parsedData[[j]])
  parsedData[[j]] <- gsub("3⃣", "키캡 숫자 3", parsedData[[j]])
  parsedData[[j]] <- gsub("4⃣", "키캡 숫자 4", parsedData[[j]])
  parsedData[[j]] <- gsub("5⃣", "키캡 숫자 5", parsedData[[j]])
  parsedData[[j]] <- gsub("6⃣", "키캡 숫자 6", parsedData[[j]])
  parsedData[[j]] <- gsub("7⃣", "키캡 숫자 7", parsedData[[j]])
  parsedData[[j]] <- gsub("8⃣", "키캡 숫자 8", parsedData[[j]])
  parsedData[[j]] <- gsub("9⃣", "키캡 숫자 9", parsedData[[j]])
  parsedData[[j]] <- gsub("🔟", "키 캡 10", parsedData[[j]])
  parsedData[[j]] <- gsub("🔢", "숫자 입력 기호", parsedData[[j]])
  parsedData[[j]] <- gsub("▶", "오른쪽을 가리키는 검은색 삼각형", parsedData[[j]])
  parsedData[[j]] <- gsub("⏸", "이중 세로 막대", parsedData[[j]])
  parsedData[[j]] <- gsub("⏯", "오른쪽을 가리키는 삼각형과 이중 세로 막대", parsedData[[j]])
  parsedData[[j]] <- gsub("⏹", "정지 사각형", parsedData[[j]])
  parsedData[[j]] <- gsub("⏺", "녹음 원", parsedData[[j]])
  parsedData[[j]] <- gsub("⏏", "꺼내기 기호", parsedData[[j]])
  parsedData[[j]] <- gsub("⏭", "오른쪽을 가리키는 이중 삼각형과 세로 막대", parsedData[[j]])
  parsedData[[j]] <- gsub("⏮", "왼쪽을 가리키는 이중 삼각형과 세로 막대", parsedData[[j]])
  parsedData[[j]] <- gsub("⏩", "오른쪽을 가리키는 검은색 이중 삼각형", parsedData[[j]])
  parsedData[[j]] <- gsub("⏪", "왼쪽을 가리키는 검은색 이중 삼각형", parsedData[[j]])
  parsedData[[j]] <- gsub("🔀", "서로 교차하는 오른쪽 화살표", parsedData[[j]])
  parsedData[[j]] <- gsub("🔁", "시계 방향으로 오른쪽과 왼쪽으로 각각 순환하는 열린 화살표", parsedData[[j]])
  parsedData[[j]] <- gsub("🔂", "시계 방향으로 오른쪽과 왼쪽으로 각각 순환하는 열린 화살표와 그 위에 있는 원문자 1", parsedData[[j]])
  parsedData[[j]] <- gsub("◀", "왼쪽을 가리키는 검은색 삼각형", parsedData[[j]])
  parsedData[[j]] <- gsub("🔼", "작은 빨간색 삼각형", parsedData[[j]])
  parsedData[[j]] <- gsub("🔽", "작은 빨간색 역삼각형", parsedData[[j]])
  parsedData[[j]] <- gsub("⏫", "위를 가리키는 검은색 이중 삼각형", parsedData[[j]])
  parsedData[[j]] <- gsub("⏬", "아래를 가리키는 검은색 이중 삼각형", parsedData[[j]])
  parsedData[[j]] <- gsub("➡", "검은색 오른쪽 화살표", parsedData[[j]])
  parsedData[[j]] <- gsub("⬅", "검은색 왼쪽 화살표", parsedData[[j]])
  parsedData[[j]] <- gsub("⬆", "검은색 위 화살표", parsedData[[j]])
  parsedData[[j]] <- gsub("⬇", "검은색 아래 화살표", parsedData[[j]])
  parsedData[[j]] <- gsub("↗", "북동쪽 화살표", parsedData[[j]])
  parsedData[[j]] <- gsub("↘", "남동쪽 화살표", parsedData[[j]])
  parsedData[[j]] <- gsub("↙", "남서쪽 화살표", parsedData[[j]])
  parsedData[[j]] <- gsub("↖", "북서쪽 화살표", parsedData[[j]])
  parsedData[[j]] <- gsub("↕", "상하 양방향 화살표", parsedData[[j]])
  parsedData[[j]] <- gsub("↔", "좌우 양방향 화살표", parsedData[[j]])
  parsedData[[j]] <- gsub("🔄", "시계 반대 방향으로 위아래로 각각 순환하는 열린 화살표", parsedData[[j]])
  parsedData[[j]] <- gsub("↪", "오른쪽을 가리키는 갈고리 화살표", parsedData[[j]])
  parsedData[[j]] <- gsub("↩", "갈고리가 있는 왼쪽 방향의 화살표", parsedData[[j]])
  parsedData[[j]] <- gsub("🔃", "시계 방향으로 위아래로 각각 순환하는 열린 화살표", parsedData[[j]])
  parsedData[[j]] <- gsub("⤴", "오른쪽을 가리키다가 위로 꺾어지는 화살표", parsedData[[j]])
  parsedData[[j]] <- gsub("⤵", "오른쪽을 가리키다가 아래로 꺾어지는 화살표", parsedData[[j]])
  parsedData[[j]] <- gsub("#⃣", "키캡 숫자 기호", parsedData[[j]])
  parsedData[[j]] <- gsub("*⃣", "키캡 별표", parsedData[[j]])
  parsedData[[j]] <- gsub("ℹ", "안내소", parsedData[[j]])
  parsedData[[j]] <- gsub("🔤", "라틴어 문자 입력 기호", parsedData[[j]])
  parsedData[[j]] <- gsub("🔡", "라틴어 소문자 입력 기호", parsedData[[j]])
  parsedData[[j]] <- gsub("🔠", "라틴어 대문자 입력 기호", parsedData[[j]])
  parsedData[[j]] <- gsub("🔣", "기호 입력 기호", parsedData[[j]])
  parsedData[[j]] <- gsub("🎵", "음표", parsedData[[j]])
  parsedData[[j]] <- gsub("🎶", "여러 개의 음표", parsedData[[j]])
  parsedData[[j]] <- gsub("〰", "물결 대시", parsedData[[j]])
  parsedData[[j]] <- gsub("➰", "한 번 꼬인 선", parsedData[[j]])
  parsedData[[j]] <- gsub("✔", "굵은 체크표시", parsedData[[j]])
  parsedData[[j]] <- gsub("➕", "굵은 덧셈 기호", parsedData[[j]])
  parsedData[[j]] <- gsub("➖", "굵은 뺄셈 기호", parsedData[[j]])
  parsedData[[j]] <- gsub("➗", "굵은 나눗셈 기호", parsedData[[j]])
  parsedData[[j]] <- gsub("✖", "굵은 곱셈 표시", parsedData[[j]])
  parsedData[[j]] <- gsub("💲", "굵은 달러 기호", parsedData[[j]])
  parsedData[[j]] <- gsub("💱", "환전", parsedData[[j]])
  parsedData[[j]] <- gsub("🔚", "왼쪽 화살표가 위에 있는 END", parsedData[[j]])
  parsedData[[j]] <- gsub("🔙", "왼쪽 화살표가 위에 있는 BACK", parsedData[[j]])
  parsedData[[j]] <- gsub("🔛", "좌우 양방향 화살표가 위에 있는 ON!", parsedData[[j]])
  parsedData[[j]] <- gsub("🔝", "위 화살표가 위에 있는 TOP", parsedData[[j]])
  parsedData[[j]] <- gsub("🔜", "오른쪽 화살표가 위에 있는 SOON", parsedData[[j]])
  parsedData[[j]] <- gsub("☑", "체크표시가 있는 정사각형", parsedData[[j]])
  parsedData[[j]] <- gsub("🔘", "라디오 버튼", parsedData[[j]])
  parsedData[[j]] <- gsub("⚪", "중간 크기의 흰색 원", parsedData[[j]])
  parsedData[[j]] <- gsub("⚫", "중간 크기의 검은색 원", parsedData[[j]])
  parsedData[[j]] <- gsub("🔴", "큰 빨간색 원", parsedData[[j]])
  parsedData[[j]] <- gsub("🔵", "큰 파란색 원", parsedData[[j]])
  parsedData[[j]] <- gsub("🔸", "작은 주황색 마름모", parsedData[[j]])
  parsedData[[j]] <- gsub("🔹", "작은 파란색 마름모", parsedData[[j]])
  parsedData[[j]] <- gsub("🔶", "큰 주황색 마름모", parsedData[[j]])
  parsedData[[j]] <- gsub("🔷", "큰 파란색 마름모", parsedData[[j]])
  parsedData[[j]] <- gsub("🔺", "빨간색 삼각형", parsedData[[j]])
  parsedData[[j]] <- gsub("▪", "작은 검은색 정사각형", parsedData[[j]])
  parsedData[[j]] <- gsub("▫", "작은 흰색 정사각형", parsedData[[j]])
  parsedData[[j]] <- gsub("⬛", "큰 검은색 정사각형", parsedData[[j]])
  parsedData[[j]] <- gsub("⬜", "큰 흰색 정사각형", parsedData[[j]])
  parsedData[[j]] <- gsub("🔻", "빨간색 역삼각형", parsedData[[j]])
  parsedData[[j]] <- gsub("◼", "중간 크기의 검은색 정사각형", parsedData[[j]])
  parsedData[[j]] <- gsub("◻", "중간 크기의 흰색 정사각형", parsedData[[j]])
  parsedData[[j]] <- gsub("◾", "중소형의 검은색 정사각형", parsedData[[j]])
  parsedData[[j]] <- gsub("◽", "중소형의 흰색 정사각형", parsedData[[j]])
  parsedData[[j]] <- gsub("🔲", "정사각형 검은색 버튼", parsedData[[j]])
  parsedData[[j]] <- gsub("🔳", "정사각형 흰색 버튼", parsedData[[j]])
  parsedData[[j]] <- gsub("🔈", "스피커", parsedData[[j]])
  parsedData[[j]] <- gsub("🔉", "하나의 음파가 있는 스피커", parsedData[[j]])
  parsedData[[j]] <- gsub("🔊", "세 개의 음파가 있는 스피커", parsedData[[j]])
  parsedData[[j]] <- gsub("🔇", "스피커 사용 중지", parsedData[[j]])
  parsedData[[j]] <- gsub("📣", "응원 메가폰", parsedData[[j]])
  parsedData[[j]] <- gsub("📢", "확성기", parsedData[[j]])
  parsedData[[j]] <- gsub("🔔", "종", parsedData[[j]])
  parsedData[[j]] <- gsub("🔕", "종 사용 중지", parsedData[[j]])
  parsedData[[j]] <- gsub("🃏", "블랙 조커 카드", parsedData[[j]])
  parsedData[[j]] <- gsub("🀄", "마작패 붉은 용", parsedData[[j]])
  parsedData[[j]] <- gsub("♠", "검은색 스페이드", parsedData[[j]])
  parsedData[[j]] <- gsub("♣", "검은색 클로버", parsedData[[j]])
  parsedData[[j]] <- gsub("♥", "검은색 하트", parsedData[[j]])
  parsedData[[j]] <- gsub("♦", "검은색 다이아몬드", parsedData[[j]])
  parsedData[[j]] <- gsub("🎴", "화투", parsedData[[j]])
  parsedData[[j]] <- gsub("👁🗨", "말풍선 속의 눈", parsedData[[j]])
  parsedData[[j]] <- gsub("🗨", "왼쪽 말풍선", parsedData[[j]])
  parsedData[[j]] <- gsub("💭", "생각 풍선", parsedData[[j]])
  parsedData[[j]] <- gsub("🗯", "오른쪽 분노 말풍선", parsedData[[j]])
  parsedData[[j]] <- gsub("💬", "말풍선", parsedData[[j]])
  parsedData[[j]] <- gsub("🕐", "1시를 가리키는 시계", parsedData[[j]])
  parsedData[[j]] <- gsub("🕑", "2시를 가리키는 시계", parsedData[[j]])
  parsedData[[j]] <- gsub("🕒", "3시를 가리키는 시계", parsedData[[j]])
  parsedData[[j]] <- gsub("🕓", "4시를 가리키는 시계", parsedData[[j]])
  parsedData[[j]] <- gsub("🕔", "5시를 가리키는 시계", parsedData[[j]])
  parsedData[[j]] <- gsub("🕕", "6시를 가리키는 시계", parsedData[[j]])
  parsedData[[j]] <- gsub("🕖", "7시를 가리키는 시계", parsedData[[j]])
  parsedData[[j]] <- gsub("🕗", "8시를 가리키는 시계", parsedData[[j]])
  parsedData[[j]] <- gsub("🕘", "9시를 가리키는 시계", parsedData[[j]])
  parsedData[[j]] <- gsub("🕙", "10시를 가리키는 시계", parsedData[[j]])
  parsedData[[j]] <- gsub("🕚", "11시를 가리키는 시계", parsedData[[j]])
  parsedData[[j]] <- gsub("🕛", "12시를 가리키는 시계", parsedData[[j]])
  parsedData[[j]] <- gsub("🕜", "1시 30분을 가리키는 시계", parsedData[[j]])
  parsedData[[j]] <- gsub("🕝", "2시 30분을 가리키는 시계", parsedData[[j]])
  parsedData[[j]] <- gsub("🕞", "3시 30분을 가리키는 시계", parsedData[[j]])
  parsedData[[j]] <- gsub("🕟", "4시 30분을 가리키는 시계", parsedData[[j]])
  parsedData[[j]] <- gsub("🕠", "5시 30분을 가리키는 시계", parsedData[[j]])
  parsedData[[j]] <- gsub("🕡", "6시 30분을 가리키는 시계", parsedData[[j]])
  parsedData[[j]] <- gsub("🕢", "7시 30분을 가리키는 시계", parsedData[[j]])
  parsedData[[j]] <- gsub("🕣", "8시 30분을 가리키는 시계", parsedData[[j]])
  parsedData[[j]] <- gsub("🕤", "9시 30분을 가리키는 시계", parsedData[[j]])
  parsedData[[j]] <- gsub("🕥", "10시 30분을 가리키는 시계", parsedData[[j]])
  parsedData[[j]] <- gsub("🕦", "11시 30분을 가리키는 시계", parsedData[[j]])
  parsedData[[j]] <- gsub("🕧", "12시 30분을 가리키는 시계", parsedData[[j]])
}

# 이모지 한글로 변환된 데이터 확인하기
View(parsedData)

# 이모지 전처리 완료된 데이터 엑셀파일로 저장하기
options(encoding="UTF-8")
filePathName = paste("/Users/kei/Desktop/180725/emoji_total_0725.csv", sep="")
write.table(parsedData, filePathName, sep=",",row.names=FALSE)
